#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width        4
bspc config top_padding         2
bspc config window_gap          12
bspc config split_ratio         0.52
bspc config focused_border_color "#eb1f92"

# mouse resize and move windows
# use alt + right click or left click

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

# dunst
$HOME/.config/dunst/dunstrc &

# picom
picom &

# polybar
$HOME/.config/polybar/launch.sh &

# sxhkd
sxhkd &

# feh wallpaper
feh --bg-fill ~/Pictures/Wallpapers/shopping.png
